### ISSUE TITLE
UI/UX - Création composant prototype

### ISSUE THREAD

**Issue by quinteirosm** [C-Super/appY-Frontend#5]
Must be done
- [ ] C-Super/appY-Frontend#4 

Then
- [x] C-Super/appY-Frontend#6

- [ ] C-Super/appY-Backend#5 mettre dans to do

**Comment by quinteirosm** [comment]
then 2 -> https://github.com/orgs/C-Super/projects/8/views/1?pane=issue&itemId=57961643
